version: '3.8'
services:
  application:
    container_name: myapplication
    build:
      context: .
      dockerfile: Dockerfile
      target: php
    ports:
      - 8007:8000
    restart: unless-stopped
    volumes:
      - ./src:/var/www/laravel